language: node_js
node_js:
  - "9"
before_script:
  - touch modules/Database/system.db
  - ./node_modules/.bin/sequelize db:migrate
  - ./node_modules/.bin/sequelize db:seed:all
  - mkdir keys
script:
  - npm run lint
  - npm start &>start.log &
  - sleep 20
  - jobs
  - kill %1
  - node isStartHealthy.js
after_script:
- cat start.log
- rm -f start.log