services:
  graph_db:
    container_name: ot_node_graph_db
    image: khaller/graphdb-free:latest
    expose:
      - 7200
    network_mode: host

  mysql:
    container_name: mysql_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - 3306
    command: >
       bash -c "
       mysql -u root -ppassword -e "CREATE DATABASE operationaldb /*\!40100 DEFAULT CHARACTER SET utf8 */; update mysql.user set plugin = 'mysql_native_password' where User='root'/*\!40100 DEFAULT CHARACTER SET utf8 */; flush privileges;" && npx sequelize --config=./config/sequelizeConfig.js db:migrate

       "
    network_mode: host
#  ot_node_v6:
#    container_name: ot_node_v6
#    build: .
#    expose:
#      - 8900
#      - 9000
#    command: >
#       bash -c "
#        supervisord -c /ot-node/current/supervisord.conf                
#        "
#    volumes:
#      - .origintrail_noderc:/ot-node/current/.origintrail_noderc
#    network_mode: host
    
