version: '3'
services:
  graphdb:
    container_name: graphdb
    image: khaller/graphdb-free:latest
    expose:
      - 7200
    network_mode: host

  ot-node:
    depends_on:
      - graphdb
    container_name: ot-node
    build: .
    expose:
      - 8900
      - 9000
    command: >
       bash -c "
       service mariadb start &&
        forever index.js                
        "
    volumes:
      - .origintrail_noderc:/ot-node/current/.origintrail_noderc
      - /certs/:/ot-node/current/certs/
    network_mode: host
    
