version: "3"
services:
  graph_db:
    container_name: ot_node_graph_db
    image: khaller/graphdb-free:latest
    expose:
      - 7200
    network_mode: host


  ot_node_v6:
    container_name: ot_node_v6
    build: .
    expose:
      - 8900
      - 9000
    command: >
       bash -c "
        npm install -g --silent json-stable-stringify &&
        service mysql restart && 
        supervisord -c /ot-node/current/supervisord.conf                
        "
    volumes:
      - .origintrail_noderc:/ot-node/current/.origintrail_noderc
    network_mode: host
    
