version: "3.9"
services:
  graph_db:
    image: khaller/graphdb-free:latest
    expose:
      - 7200
    network_mode: host


  ot_node_v6:
    build: .
    expose:
      - 3306
      - 8900
      - 9000
    network_mode: host
    depends_on:
      graph_db:
        condition: service_healthy