version: '3'
services:

  mysql:
    build:
      dockerfile: Alpine.Dockerfile
      context: .
    image: alpine:latest
    container_name: ot-node
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=operationaldb
    
    ports:
      - "3306"