services:
  graph_db:
    container_name: ot_node_graph_db
    image: khaller/graphdb-free:latest
    expose:
      - 7200
    network_mode: host

  ot_node_v6:
    depends_on:
      - graph_db
    container_name: ot_node_v6
    build: .
    expose:
      - 8900
      - 9000
    command: >
       bash -c "
       service mariadb start &&
        node index.js                
        "
    volumes:
      - .origintrail_noderc:/ot-node/current/.origintrail_noderc
      - /certs/:/ot-node/current/certs/
    network_mode: host
    
