version: "3.9"
services:
  graph_db:
    container_name: ot_node_graph_db
    image: khaller/graphdb-free:latest
    expose:
      - 7200
    network_mode: host


  ot_node_v6:
    container_name: ot_node_v6
    build: .
    expose:
      - 3306
      - 8900
      - 9000
    command: >
       bash -c "
        service mysql restart && 
        supervisord -c /ot-node/current/supervisord.conf                
        "
    network_mode: host
    