name: TEST-release

#todo this test should be execute when opening PR to prerelase/release branches
on: [pull_request]
env:
  NODE_ENV: development
  ARTIFACTS_DIR: artifacts
  CUCUMBER_ARTIFACTS_DIR: artifacts/cucumber
jobs:

  test:
    #todo think about locking the version - version should be the same as the one in official documentation
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: operationaldb
          MYSQL_USER: node
          MYSQL_PASSWORD: node-password
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      blazegraph:
        image: lyrasis/blazegraph:2.1.6
        ports:
          - 7200:7200
    strategy:
      matrix:
        #todo update to latest version
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
#      - run: mkdir -p $ARTIFACTS_DIR
#      - run: sudo chmod -R 777 $ARTIFACTS_DIR
#      - run: mkdir -p $CUCUMBER_ARTIFACTS_DIR
#      - run: sudo chmod -R 777 $CUCUMBER_ARTIFACTS_DIR
#      - run: sudo ./setup_arangodb.sh
#      - run: cp .origintrail_noderc.travis .origintrail_noderc
#      - run: npm run bootstrap
#      - run: npm run test:bdd -- --tags=@first --world-parameters '{"appDataBaseDir":"$CUCUMBER_ARTIFACTS_DIR","keepFailedArtifacts":true}';
